=== EphermeralX/Databases/XPATH_and_XSLT/Scholars.dtd
<!ELEMENT Scholars (Scholar)+>
<!ELEMENT Scholar (((Firstname,Lastname)|Fullname),Nationality,Birthplace,Age,Sex,Professions)>
<!ATTLIST Scholar SID ID #REQUIRED type CDATA #FIXED 'Scientist'>

<!ELEMENT Firstname (#PCDATA)>
<!ELEMENT Lastname (#PCDATA)>
<!ELEMENT Fullname (#PCDATA)>

<!ELEMENT Nationality (#PCDATA)>

<!ELEMENT Birthplace EMPTY>

<!ELEMENT Age (#PCDATA)>
<!ATTLIST Age Status (Alive|Dead) 'Alive'>
<!ATTLIST Age Birsthdate CDATA #REQUIRED>
<!ATTLIST Age Deathdate CDATA #IMPLIED>

<!ELEMENT Sex (#PCDATA)>

<!ELEMENT Professions (Profession+)>
<!ELEMENT Profession (#PCDATA)>

=== EphermeralX/Databases/XSLT_and_legal_issues/w4Ex.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- The XSL association-->
<?xml-stylesheet href="Scholars.xsl" type="text/xsl"?>

<!-- External DTD -->
<!DOCTYPE Scholars SYSTEM "Scholars.dtd">
<Scholars>
    <Scholar SID="cdut88031934" type="Scientist">
        <Firstname>Jane</Firstname>
        <Lastname>Goodall</Lastname>
        <Nationality>British</Nationality>
        <Birthplace/>
        <Age Birthdate="April 3, 1934" Status="Alive" Deathdate="">88</Age>
        <Sex>Female</Sex>
        <Professions>
            <Profession>
                Zoology
            </Profession>
            <Profession>
                Anthropology
            </Profession>
        </Professions>
    </Scholar>

    <Scholar SID="ucla70261946" type="Scientist">
        <Fullname>Ahmed Zewail</Fullname>
        <Nationality>Egyption &amp; American</Nationality>
        <Birthplace/>
        <Age Birthdate="February 26, 1946" Status="Dead" Deathdate="August 2, 2016">70</Age>
        <Sex>Male</Sex>
        <Professions>
            <Profession>
                Chemistry
            </Profession>
            <Profession>
                Physics
            </Profession>
        </Professions>
    </Scholar>
</Scholars>

=== EphermeralX/Databases/XPATH_and_XSLT/w3Ex1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- External DTD -->
<!DOCTYPE Scholars SYSTEM "Scholars.dtd">
<Scholars>
    <Scholar SID="cdut20191801" type="Scientist">
        <Firstname>Tony</Firstname>
        <Lastname>Cheng</Lastname>
        <Nationality>China</Nationality>
        <Birthplace />
        <Age Birsthdate="2000-11-19" Status="Alive" Deathdate="Unknown">21</Age>
        <Sex>Male</Sex>
        <Professions>
            <Profession>
                Student
            </Profession>
            <Profession>
                Programmer
            </Profession>
        </Professions>
    </Scholar>

    <Scholar SID="ucla20191802" type="Scientist">
        <Fullname>Amit Sahai</Fullname>
        <Nationality>American</Nationality>
        <Birthplace />
        <Age Birsthdate="Unknown" Status="Alive" Deathdate="Unknown">45</Age>
        <Sex>Male</Sex>
        <Professions>
            <Profession>
                Professor
            </Profession>
        </Professions>
    </Scholar>
</Scholars>
