=== EphermeralX/Databases/Coursework1/transactions.dtd
<!--DTD FILE -->
<!ELEMENT Transactions (shop+)>

<!ELEMENT shop (Date*)>
<!ATTLIST shop number CDATA #REQUIRED>

<!ELEMENT Date (Transaction+)>
<!ATTLIST Date date CDATA #REQUIRED>

<!ELEMENT Transaction (value,key,customer*)>
<!ATTLIST Transaction transactionID CDATA #REQUIRED>

<!ELEMENT value (#PCDATA)>
<!ATTLIST value currency CDATA #REQUIRED>

<!ELEMENT customer (prefix,lastName,givenName,addressID)>
<!ATTLIST customer customerID CDATA #REQUIRED>

<!ELEMENT key (#PCDATA)>

<!ELEMENT prefix (#PCDATA)>
<!ELEMENT lastName (#PCDATA)>
<!ELEMENT givenName (#PCDATA)>
<!ELEMENT addressID (#PCDATA)>

<!ENTITY mrs "Mrs" >
<!ENTITY mr "Mr" >
<!ENTITY mrs "Miss" >
<!ENTITY dr "Dr" >
<!ENTITY key "oTMWj2i5IDXy3xYmut1G">

=== EphermeralX/Databases/Coursework1/output.xml
<?xml version="1.0"?>
<!DOCTYPE Transactions SYSTEM "transactions.dtd">
<Transactions>
	<shop number="1">
		<Date date="01/11/2019">
			<Transaction transactionID="BjYAtd7lmEOlQUVy">
				<value currency="gbp">61.33</value>
				<key>oTMWj2i5IDXy3xYmut1G</key>
				<customer customerID="8BLOJZWL">
					<prefix>Mr </prefix>
					<lastName>Arnold</lastName>
					<givenName>Jaydon</givenName>
					<addressID>551640</addressID>
				</customer>
			</Transaction>
			<Transaction transactionID="xiFZUFOv8J8zKqyU">
				<value currency="gbp">19.76</value>
				<key>oTMWj2i5IDXy3xYmut1G</key>
				<customer customerID="BQ0JG15U">
					<prefix>Miss</prefix>
					<lastName>Witherspoon</lastName>
					<givenName>Wisdom</givenName>
					<addressID>306679</addressID>
				</customer>
			</Transaction>
			<Transaction transactionID="7Yog0IVnlVbOGIQX">
				<value currency="gbp">54.12</value>
				<key>oTMWj2i5IDXy3xYmut1G</key>
				<customer customerID="4FI1TAJW">
					<prefix>Mr </prefix>
					<lastName>Bellamy</lastName>
					<givenName>Sawyer</givenName>
					<addressID>792091</addressID>
				</customer>
			</Transaction>
			<Transaction transactionID="6vtTiqxOcrZn6DEU">
				<value currency="gbp">68.06</value>
				<key>oTMWj2i5IDXy3xYmut1G</key>
				<customer customerID="EO1KDAFV">
					<prefix>Mrs</prefix>
					<lastName>MacConnell</lastName>
					<givenName>Selina</givenName>
					<addressID>62588</addressID>
				</customer>
			</Transaction>
			<Transaction transactionID="SgjnoLMH9VEVixHs">
				<value currency="gbp">57.94</value>
				<key>oTMWj2i5IDXy3xYmut1G</key>
				<customer customerID="OGUQVY70">
					<prefix>Mrs</prefix>
					<lastName>Wilton</lastName>
					<givenName>Starla</givenName>
					<addressID>483243</addressID>
				</customer>
			</Transaction>
			<Transaction transactionID="XhEO9gTFG8RUY3IU">
				<value currency="gbp">1.42</value>
				<key>oTMWj2i5IDXy3xYmut1G</key>
			</Transaction>
			<Transaction transactionID="KlWY6fCOZKdkJDsD">
				<value currency="gbp">92.62</value>
				<key>oTMWj2i5IDXy3xYmut1G</key>
			</Transaction>
			<Transaction transactionID="Kp7ZbWl1HwFWhbFZ">
				<value currency="gbp">45.31</value>
				<key>oTMWj2i5IDXy3xYmut1G</key>
			</Transaction>
			<Transaction transactionID="rvBkzjA7MvAyYS8q">
				<value currency="gbp">36.29</value>
				<key>oTMWj2i5IDXy3xYmut1G</key>
			</Transaction>
			<Transaction transactionID="02OcmusE2z7101nk">
				<value currency="gbp">38.51</value>
				<key>oTMWj2i5IDXy3xYmut1G</key>
			</Transaction>
		</Date>
		<Date date="02/11/2019">
			<Transaction transactionID="IX9UspYJgYTYwtbI">
				<value currency="gbp">13.84</value>
				<key>oTMWj2i5IDXy3xYmut1G</key>
				<customer customerID="A25S3UU6">
					<prefix>Mrs</prefix>
					<lastName>Tobias</lastName>
					<givenName>Talia</givenName>
					<addressID>790366</addressID>
				</customer>
			</Transaction>
			<Transaction transactionID="1Lng8B0uDphSQhu4">
				<value currency="gbp">0.89</value>
				<key>oTMWj2i5IDXy3xYmut1G</key>
				<customer customerID="QQASCC8J">
					<prefix>Mrs</prefix>
					<lastName>Dhuibh</lastName>
					<givenName>Minta</givenName>
					<addressID>331249</addressID>
				</customer>
			</Transaction>
			<Transaction transactionID="McnBd7VFUUqkBszp">
				<value currency="gbp">80.21</value>
				<key>oTMWj2i5IDXy3xYmut1G</key>
				<customer customerID="Z0A07AOV">
					<prefix>Ms</prefix>
					<lastName>Stringer</lastName>
					<givenName>Coretta</givenName>
					<addressID>64056</addressID>
				</customer>
			</Transaction>
			<Transaction transactionID="FdHLlG1RAcnSJf4p">
				<value currency="gbp">43.2</value>
				<key>oTMWj2i5IDXy3xYmut1G</key>
				<customer customerID="9J1R7LKH">
					<prefix>Mr </prefix>
					<lastName>Simpson</lastName>
					<givenName>Darcy</givenName>
					<addressID>546250</addressID>
				</customer>
			</Transaction>
			<Transaction transactionID="JvVoaPj4lZyKiQuc">
				<value currency="gbp">40.29</value>
				<key>oTMWj2i5IDXy3xYmut1G</key>
			</Transaction>
			<Transaction transactionID="mKRBTHMdzeS2AlbE">
				<value currency="gbp">8.35</value>
				<key>oTMWj2i5IDXy3xYmut1G</key>
			</Transaction>
			<Transaction transactionID="SvnYTwn2eowMAEvL">
				<value currency="gbp">76.04</value>
				<key>oTMWj2i5IDXy3xYmut1G</key>
			</Transaction>
			<Transaction transactionID="w5IkrxUu6TXsAkaw">
				<value currency="gbp">12.27</value>
				<key>oTMWj2i5IDXy3xYmut1G</key>
			</Transaction>
			<Transaction transactionID="xE67z4a83j1aFEfN">
				<value currency="gbp">35.98</value>
				<key>oTMWj2i5IDXy3xYmut1G</key>
			</Transaction>
			<Transaction transactionID="PefmwmiklcrkeI5e">
				<value currency="gbp">56.37</value>
				<key>oTMWj2i5IDXy3xYmut1G</key>
			</Transaction>
			<Transaction transactionID="H5dyVQlkUp2p85Qd">
				<value currency="gbp">64.5</value>
				<key>oTMWj2i5IDXy3xYmut1G</key>
			</Transaction>
			<Transaction transactionID="LjmDkVnOFzaoJXTC">
				<value currency="gbp">32.76</value>
				<key>oTMWj2i5IDXy3xYmut1G</key>
			</Transaction>
		</Date>
		<Date date="03/11/2019">
			<Transaction transactionID="9y56RANfMNM9KTkK">
				<value currency="gbp">35.33</value>
				<key>oTMWj2i5IDXy3xYmut1G</key>
				<customer customerID="NFP1RIH5">
					<prefix>Mr </prefix>
					<lastName>Lyon</lastName>
					<givenName>Laz</givenName>
					<addressID>259820</addressID>
				</customer>
			</Transaction>
			<Transaction transactionID="MPRDuvVBW3EYul6K">
				<value currency="gbp">34.12</value>
				<key>oTMWj2i5IDXy3xYmut1G</key>
				<customer customerID="TUUSA0SI">
					<prefix>Mr </prefix>
					<lastName>Scriven</lastName>
					<givenName>Gib</givenName>
					<addressID>86916</addressID>
				</customer>
			</Transaction>
			<Transaction transactionID="52m2IVzGHpcS2a2N">
				<value currency="gbp">19.78</value>
				<key>oTMWj2i5IDXy3xYmut1G</key>
				<customer customerID="2YOK85QF">
					<prefix>Dr</prefix>
					<lastName>Foss</lastName>
					<givenName>Kaycee</givenName>
					<addressID>513089</addressID>
				</customer>
			</Transaction>
			<Transaction transactionID="U3nFii6UySqlCxb1">
				<value currency="gbp">23.51</value>
				<key>oTMWj2i5IDXy3xYmut1G</key>
			</Transaction>
			<Transaction transactionID="suY8CnWiIMtaggrw">
				<value currency="gbp">66.15</value>
				<key>oTMWj2i5IDXy3xYmut1G</key>
			</Transaction>
			<Transaction transactionID="83awZ7moVAnWROzt">
				<value currency="gbp">7.69</value>
				<key>oTMWj2i5IDXy3xYmut1G</key>
			</Transaction>
			<Transaction transactionID="mup7aknOPcslSgOs">
				<value currency="gbp">51.13</value>
				<key>oTMWj2i5IDXy3xYmut1G</key>
			</Transaction>
			<Transaction transactionID="2OtBDgddoUUpehCa">
				<value currency="gbp">97.36</value>
				<key>oTMWj2i5IDXy3xYmut1G</key>
			</Transaction>
		</Date>
	</shop>
	<shop number="2">
		<Date date="01/11/2019">
			<Transaction transactionID="aQ27lMvfnlzY4mkx">
				<value currency="gbp">54.21</value>
				<key>oTMWj2i5IDXy3xYmut1G</key>
				<customer customerID="DR18OCFI">
					<prefix>Mrs</prefix>
					<lastName>Briain</lastName>
					<givenName>Hailie</givenName>
					<addressID>95280</addressID>
				</customer>
			</Transaction>
			<Transaction transactionID="1ygOIpJ6Tf2HB72e">
				<value currency="gbp">57.43</value>
				<key>oTMWj2i5IDXy3xYmut1G</key>
				<customer customerID="31F9PCQD">
					<prefix>Mr </prefix>
					<lastName>Trask</lastName>
					<givenName>Fearchar</givenName>
					<addressID>13287</addressID>
				</customer>
			</Transaction>
			<Transaction transactionID="2lZ75q0FrSpcREjs">
				<value currency="gbp">49.49</value>
				<key>oTMWj2i5IDXy3xYmut1G</key>
				<customer customerID="FDCXOH0M">
					<prefix>Mrs</prefix>
					<lastName>Bateson</lastName>
					<givenName>Karissa</givenName>
					<addressID>468126</addressID>
				</customer>
			</Transaction>
			<Transaction transactionID="oTfh5Dg0ACCGG0SH">
				<value currency="gbp">8.59</value>
				<key>oTMWj2i5IDXy3xYmut1G</key>
				<customer customerID="BA1LBL11">
					<prefix>Mr </prefix>
					<lastName>Shaughnessy</lastName>
					<givenName>Paddy</givenName>
					<addressID>303203</addressID>
				</customer>
			</Transaction>
			<Transaction transactionID="xNcmC90pdXYcdUNF">
				<value currency="gbp">72.96</value>
				<key>oTMWj2i5IDXy3xYmut1G</key>
				<customer customerID="DOWK75O4">
					<prefix>Mr </prefix>
					<lastName>Boyle</lastName>
					<givenName>Cohen</givenName>
					<addressID>92016</addressID>
				</customer>
			</Transaction>
			<Transaction transactionID="4oZAWTFBGOuNtjm6">
				<value currency="gbp">56.13</value>
				<key>oTMWj2i5IDXy3xYmut1G</key>
				<customer customerID="KKDLTC4B">
					<prefix>Ms</prefix>
					<lastName>Britton</lastName>
					<givenName>Estella</givenName>
					<addressID>946382</addressID>
				</customer>
			</Transaction>
			<Transaction transactionID="L72fYINuLfbm61yr">
				<value currency="gbp">57.26</value>
				<key>oTMWj2i5IDXy3xYmut1G</key>
				<customer customerID="CMNY0DKI">
					<prefix>Mr </prefix>
					<lastName>Hopper</lastName>
					<givenName>Tadhg</givenName>
					<addressID>787046</addressID>
				</customer>
			</Transaction>
			<Transaction transactionID="f2bXNaWqlGR8k2kh">
				<value currency="gbp">13.94</value>
				<key>oTMWj2i5IDXy3xYmut1G</key>
				<customer customerID="IE6T80M6">
					<prefix>Mr </prefix>
					<lastName>Alfredson</lastName>
					<givenName>Malakai</givenName>
					<addressID>704817</addressID>
				</customer>
			</Transaction>
			<Transaction transactionID="jybwh5EroaL4FfJs">
				<value currency="gbp">75.92</value>
				<key>oTMWj2i5IDXy3xYmut1G</key>
				<customer customerID="0V1XOKLR">
					<prefix>Mr </prefix>
					<lastName>Harley</lastName>
					<givenName>Monroe</givenName>
					<addressID>882651</addressID>
				</customer>
